export const MOCK_DATA = [
  {
    "login": "AustinLynes",
    "id": 50124157,
    "node_id": "MDQ6VXNlcjUwMTI0MTU3",
    "avatar_url": "https://avatars1.githubusercontent.com/u/50124157?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/AustinLynes",
    "html_url": "https://github.com/AustinLynes",
    "followers_url": "https://api.github.com/users/AustinLynes/followers",
    "following_url": "https://api.github.com/users/AustinLynes/following{/other_user}",
    "gists_url": "https://api.github.com/users/AustinLynes/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/AustinLynes/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/AustinLynes/subscriptions",
    "organizations_url": "https://api.github.com/users/AustinLynes/orgs",
    "repos_url": "https://api.github.com/users/AustinLynes/repos",
    "events_url": "https://api.github.com/users/AustinLynes/events{/privacy}",
    "received_events_url": "https://api.github.com/users/AustinLynes/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Austin Lynes",
    "company": null,
    "blog": "",
    "location": "Bend Oregon",
    "email": null,
    "hireable": true,
    "bio": "I am Software Engineer Learning at Lambda School Online! I am versed in, HTML5, CSS3, ES6 Javascript, React,(Hooks & Classes)\r\n",
    "public_repos": 42,
    "public_gists": 0,
    "followers": 2,
    "following": 4,
  }
]